# Generated by Django 2.2.8 on 2020-01-14 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('type_of_activity', models.CharField(blank=True, choices=[('Жора', 'Жора'), ('Интернет-магазин', 'Интернет-магазин'), ('Стройматреиалы', 'Стройматериалы'), ('Хозяйственный', 'Хозяйственный'), ('Магазин', 'Магазин'), ('Одежда', 'Одежда'), ('Продукты', 'Продукты'), ('Ресторан', 'Ресторан'), ('Сервис', 'Сервис'), ('Салон красоты', 'Салон красоты'), ('СМЦ', 'СМЦ'), ('Цветочный ряд', 'Цветочный ряд')], max_length=50, null=True, verbose_name='вид деятельности')),
                ('landlord', models.CharField(blank=True, max_length=255, null=True, verbose_name='арендодатель')),
                ('contacts', models.CharField(blank=True, max_length=155, null=True, verbose_name='контакты')),
                ('payment', models.IntegerField(default=0, verbose_name='оплата')),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('tel_num', models.CharField(max_length=155, verbose_name='номер тел.')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('salary', models.IntegerField(default=0, verbose_name='ЗП')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата открытия')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('iep_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИП')),
                ('ident_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('type_of_activity', models.CharField(choices=[('Цветы', 'Цветы'), ('Цветы солдат', 'Цветы солдат'), ('СМЦ', 'СМЦ'), ('СМЦ солдат', 'СМЦ солдат'), ('Одиночка', 'Одиночка'), ('Одиночка солдат', 'Одиночка солдат')], max_length=50, verbose_name='вид деятельности')),
                ('tel_number', models.CharField(blank=True, default='+7', max_length=12, null=True, verbose_name='номер тел.')),
                ('el_key', models.BooleanField(default=True, verbose_name='электронный ключ')),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'ИП',
                'verbose_name_plural': 'ИП',
                'db_table': 'individual_entrepreneur',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата публикации')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('incoming', models.IntegerField(blank=True, default=0, null=True, verbose_name='приход')),
                ('expense', models.IntegerField(blank=True, default=0, null=True, verbose_name='расход')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='баланс')),
                ('description', models.CharField(max_length=255, verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата постановки')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('number_of_terminal', models.CharField(max_length=100, verbose_name='номер терминала')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terminal', to='docbiz_app.Clients', verbose_name='клиент')),
                ('iep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Терминалы',
                'verbose_name_plural': 'Терминалы',
                'db_table': 'terminals',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneurSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата заполнения')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='коментарий')),
                ('amount', models.IntegerField(default=0, verbose_name='ЗП')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'ИП ЗП',
                'verbose_name_plural': 'ИП ЗП',
                'db_table': 'iep_salary',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneurInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата заполнения')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='пароль')),
                ('bank', models.CharField(blank=True, choices=[('Альфа-банк', 'Альфа-банк'), ('БИНБАНК', 'БИНБАНК'), ('Возрождение', 'Возрождение'), ('Промсвязьбанк', 'Промсвязьбанк'), ('ВТБ', 'ВТБ'), ('Локо-банк', 'Локо-банк'), ('Модуль-банк', 'Модуль-банк'), ('Райффайзен-банк', 'Райффайзен-банк'), ('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Точка', 'Точка'), ('Уралсиб', 'Уралсиб')], max_length=100, null=True, verbose_name='банк')),
                ('password_of_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='пароль карты')),
                ('codeword', models.CharField(blank=True, max_length=100, null=True, verbose_name='кодовое слово')),
                ('iep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'ИП инфо.',
                'verbose_name_plural': 'ИП инфо.',
                'db_table': 'iep_info',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneurDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата заполнения')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('debt', models.IntegerField(default=0, verbose_name='долг')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'ИП долги',
                'verbose_name_plural': 'ИП долги',
                'db_table': 'iep_debt',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_1', models.DateField(default=datetime.datetime.now, verbose_name='дата')),
                ('salary_payment_1', models.IntegerField(blank=True, default=0, null=True, verbose_name='1/2 часть')),
                ('created_date_2', models.DateField(default=datetime.datetime.now, verbose_name='дата')),
                ('salary_payment_2', models.IntegerField(blank=True, default=0, null=True, verbose_name='2/2 часть')),
                ('salary_balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='баланс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docbiz_app.Employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'ЗП сотрудника',
                'verbose_name_plural': 'ЗП сотрудника',
                'db_table': 'employee_salary',
            },
        ),
        migrations.CreateModel(
            name='Cashboxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата постановки')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('model_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='название модели')),
                ('number_of_cashbox', models.CharField(max_length=100, verbose_name='номер кассы')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashbox', to='docbiz_app.Clients', verbose_name='клиент')),
                ('iep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Кассы',
                'verbose_name_plural': 'Кассы',
                'db_table': 'cashboxes',
            },
        ),
    ]
