# Generated by Django 2.2 on 2019-08-14 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата создания')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('type_of_activity', models.CharField(choices=[('Жора', 'Жора'), ('Одежда', 'Одежда'), ('Продукты', 'Продукты'), ('Ресторан', 'Ресторан'), ('Сервис', 'Сервис'), ('СМЦ', 'СМЦ'), ('Цветочный ряд', 'Цветочный ряд')], max_length=100, verbose_name='вид деятельности')),
                ('landlord', models.CharField(blank=True, max_length=255, null=True, verbose_name='арендодатель')),
                ('payment', models.IntegerField(default=0, verbose_name='оплата')),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('tel_num', models.CharField(max_length=155, verbose_name='номер тел.')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('salary', models.CharField(max_length=155, verbose_name='ЗП')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата открытия')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('iep_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ИП')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('tel_number', models.CharField(blank=True, default='+7', max_length=12, null=True, verbose_name='номер тел.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта')),
                ('el_key', models.BooleanField(default=True, verbose_name='электронный ключ')),
                ('status', models.BooleanField(default=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'ИП',
                'verbose_name_plural': 'ИП',
                'db_table': 'individual_entrepreneur',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата публикации')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('incoming', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='приход')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='расход')),
                ('description', models.CharField(max_length=255, verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата постановки')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('number_of_terminal', models.CharField(max_length=100, verbose_name='номер терминала')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.Clients', verbose_name='клиент')),
                ('iep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Терминалы',
                'verbose_name_plural': 'Терминалы',
                'db_table': 'terminals',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneurInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата заполнения')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('bank', models.CharField(choices=[('Альфа-банк', 'Альфа-банк'), ('БИНБАНК', 'БИНБАНК'), ('ВТБ', 'ВТБ'), ('Локо-банк', 'Локо-банк'), ('Модуль-банк', 'Модуль-банк'), ('Райффайзен-банк', 'Райффайзен-банк'), ('Сбербанк', 'Сбербанк'), ('Тинькофф', 'Тинькофф'), ('Точка', 'Точка'), ('Уралсиб', 'Уралсиб')], max_length=100, verbose_name='банк')),
                ('password_of_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='пароль карты')),
                ('codeword', models.CharField(blank=True, max_length=100, null=True, verbose_name='кодовое слово')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='пароль')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'ИП инфо.',
                'verbose_name_plural': 'ИП инфо.',
                'db_table': 'iep_info',
            },
        ),
        migrations.CreateModel(
            name='Cashboxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='дата постановки')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='дата обновления')),
                ('model_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='название модели')),
                ('number_of_cashbox', models.CharField(max_length=100, verbose_name='номер кассы')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.Clients', verbose_name='клиент')),
                ('iep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.IndividualEntrepreneur', verbose_name='ИП')),
            ],
            options={
                'verbose_name': 'Кассы',
                'verbose_name_plural': 'Кассы',
                'db_table': 'cashboxes',
            },
        ),
    ]
