# Generated by Django 2.2 on 2019-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('url', models.CharField(max_length=155)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_created=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('incoming', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('desc', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
