# Generated by Django 2.2.8 on 2020-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxes',
            name='number_of_cashbox',
            field=models.CharField(max_length=100, unique=True, verbose_name='номер кассы'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='number_of_terminal',
            field=models.CharField(max_length=100, unique=True, verbose_name='номер терминала'),
        ),
    ]
