# Generated by Django 2.2 on 2019-05-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='desc',
            new_name='description',
        ),
    ]
