# Generated by Django 2.2 on 2019-10-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashs', to='docbiz_app.Clients', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneurinfo',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='логин'),
        ),
    ]
