# Generated by Django 2.2 on 2019-07-25 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casboxes',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата постановки'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата открытия'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneurinfo',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата заполнения'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата постановки'),
        ),
    ]
