# Generated by Django 2.2 on 2019-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0002_auto_20190515_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tel_num', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date_pub',
            field=models.DateTimeField(),
        ),
    ]
