# Generated by Django 2.2 on 2019-10-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0002_auto_20191001_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashbox', to='docbiz_app.Clients', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='terminal', to='docbiz_app.Clients', verbose_name='клиент'),
        ),
    ]
