# Generated by Django 2.2 on 2019-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0002_auto_20190726_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта'),
        ),
    ]
