# Generated by Django 2.2.8 on 2020-02-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0002_auto_20200217_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['created_date'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['created_date'], 'verbose_name': 'Терминалы', 'verbose_name_plural': 'Терминалы'},
        ),
        migrations.AlterField(
            model_name='clientspayment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='docbiz_app.Cashboxes', verbose_name='клиент'),
        ),
    ]
