# Generated by Django 2.2 on 2019-09-06 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0002_auto_20190829_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualentrepreneur',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата окончания'),
        ),
    ]
