# Generated by Django 2.2 on 2019-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0003_auto_20190522_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_pub',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date_up',
            field=models.DateField(auto_now=True),
        ),
    ]
