# Generated by Django 2.2 on 2019-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0003_individualentrepreneur_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='ЗП'),
        ),
    ]
