# Generated by Django 2.2 on 2019-07-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0003_auto_20190730_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='город'),
        ),
    ]
