# Generated by Django 2.2.8 on 2020-02-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0003_auto_20200217_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualentrepreneur',
            options={'ordering': ['created_date'], 'verbose_name': 'ИП', 'verbose_name_plural': 'ИП'},
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='tel_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='номер тел.'),
        ),
    ]
