# Generated by Django 2.2 on 2019-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0004_auto_20190909_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=100, verbose_name='ЗП'),
        ),
    ]
