# Generated by Django 2.2.8 on 2020-01-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0004_auto_20191212_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['created_date'], 'verbose_name': 'Транзакции', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='ident_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
