# Generated by Django 2.2 on 2019-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0004_auto_20190617_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(blank=True, choices=[('Расходы ДокБиз', 'Расходы ДокБиз'), ('Расходы Реальные', 'Расходы Реальные')], max_length=100, null=True),
        ),
    ]
