# Generated by Django 2.2.8 on 2020-05-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0005_auto_20200324_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualentrepreneur',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='iep_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ф.И.О'),
        ),
    ]
