# Generated by Django 2.2.8 on 2020-01-09 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0005_auto_20200109_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualEntrepreneurSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.now, verbose_name='')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('amount', models.IntegerField(default=0, verbose_name='')),
                ('iep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docbiz_app.IndividualEntrepreneur', verbose_name='')),
            ],
            options={
                'verbose_name': 'ИП ЗП',
                'verbose_name_plural': 'ИП ЗП',
                'db_table': 'iep_salary',
            },
        ),
    ]
