# Generated by Django 2.2 on 2019-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0005_auto_20190909_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='ЗП'),
        ),
    ]
