# Generated by Django 2.2 on 2019-09-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0006_auto_20190909_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='end_date',
        ),
    ]
