# Generated by Django 2.2.8 on 2020-05-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0006_auto_20200506_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneurdebt',
            name='iep',
        ),
        migrations.DeleteModel(
            name='ClientsPayment',
        ),
        migrations.DeleteModel(
            name='IndividualEntrepreneurDebt',
        ),
    ]
