# Generated by Django 2.2.8 on 2020-05-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbiz_app', '0007_auto_20200506_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='email',
        ),
    ]
